[General]
background=bg.mp4
type=video
font=PixelifySans
color=#fae8d8
fontSize=13
mode=hybrid 
# #There are four modes available: hybrid, image, video, and stay.

# image = random selection of image wallpapers only (png, jpg, jpeg, webp)
# video = random selection of video wallpapers only (mp4, gif)
# hybrid = combines random videos and images
# stay = ensures the wallpaper remains set after a reboot or shutdown
